# Generated by Django 5.1.6 on 2025-02-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='standard',
            field=models.CharField(max_length=10),
        ),
    ]
