# Generated by Django 5.1.6 on 2025-02-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_record_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='standard',
            field=models.IntegerField(),
        ),
    ]
