# Generated by Django 5.1.3 on 2025-01-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_formresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='standard',
            field=models.IntegerField(max_length=20),
        ),
    ]
