# Generated by Django 5.1.3 on 2025-01-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_questionbank_alter_record_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='assessment_status',
            field=models.CharField(default='Not Assessed', max_length=50),
        ),
    ]
